//export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:8080/api';
//export const ACCESS_TOKEN = 'accessToken';

const LOW_LEVEL = 1;
const MEDIUM_LEVEL = 2;
const HIGT_LEVEL = 3;  
const LOW_LEVEL_SUDDEN_BRAKIMG = 10;
const LOW_LEVEL_COLLISIONS = 15;
const LOW_LEVEL_SPEED_OR_LANE = 20;
const MEDIUM_LEVEL_SUDDEN_BRAKIMG = 6;
const MEDIUM_LEVEL_COLLISIONS = 10;
const MEDIUM_LEVEL_SPEED_OR_LANE = 12;
const HIGH_LEVEL_SUDDEN_BRAKIMG = 2;
const HIGH_LEVEL_COLLISIONS = 6;
const HIGH_LEVEL_SPEED_OR_LANE =4;

module.exports = {
    LOW_LEVEL,
    MEDIUM_LEVEL,
    HIGT_LEVEL,
    LOW_LEVEL_SUDDEN_BRAKIMG,
    LOW_LEVEL_COLLISIONS,
    LOW_LEVEL_SPEED_OR_LANE,
    MEDIUM_LEVEL_SUDDEN_BRAKIMG,
    MEDIUM_LEVEL_COLLISIONS,
    MEDIUM_LEVEL_SPEED_OR_LANE,
    HIGH_LEVEL_SUDDEN_BRAKIMG,
    HIGH_LEVEL_COLLISIONS,
    HIGH_LEVEL_SPEED_OR_LANE
};